name: test project
on: push
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         - name: get my code
           uses: actions/checkout@v3

         - name: install node
           uses: actions/setup-node@v3
           with:
              node-version: 18
         - name: install dependency
           run: yarn ci
         - name: run tests
           run: yarn test
